const Locations = {
  US: "United States",
  CA: "Canada",
  MX: "Mexico",
  GB: "United Kingdom",
  AU: "Australia",
  NZ: "New Zealand",
  IN: "India",
  JP: "Japan",
  KR: "South Korea",
  CN: "China",
  SG: "Singapore",
  HK: "Hong Kong",
  MY: "Malaysia",
  PH: "Philippines",
  TH: "Thailand",
  ID: "Indonesia",
  VN: "Vietnam",
  TW: "Taiwan",
  AR: "Argentina",
  BR: "Brazil",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
};

const Hotels = {
  "Hotel 1": "Hotel 1",
  "Hotel 2": "Hotel 2",
  "Hotel 3": "Hotel 3",
  "Hotel 4": "Hotel 4",
  "Hotel 5": "Hotel 5",
  "Hotel 6": "Hotel 6",
};
